version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017
    volumes:
      - .:/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
